# Generated by Django 5.0.3 on 2024-03-12 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('second_name', models.CharField(max_length=256)),
                ('phone', models.IntegerField(max_length=20)),
                ('email', models.EmailField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=256)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('second_name', models.CharField(max_length=256)),
                ('phone', models.IntegerField(max_length=20)),
                ('email', models.EmailField(max_length=256)),
                ('date_start_work', models.DateField()),
                ('position', models.CharField(choices=[('Seller', 'Продавец'), ('Main Seller', 'Старший продавец'), ('Boss', 'Руководитель отдела продаж')], max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SellsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_date', models.DateTimeField()),
                ('price', models.IntegerField(max_length=20)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.buyer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.seller')),
            ],
        ),
    ]
