# Generated by Django 5.0.3 on 2024-03-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sellsinfo',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sellsinfo',
            name='sell_date',
            field=models.DateField(),
        ),
    ]
